name: Run K6 Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k6_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install K6
        uses: grafana/setup-k6-action@v1

      - name: Install dependencies
        run: npm install
        
      - name: Run K6 Load Test
        run: npm run test
