name: Run K6 Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k6_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (you can adjust the version if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install K6 globally
      - name: Install K6
        uses: grafana/setup-k6-action@v1

      # Step 4: Install dependencies from package.json
      - name: Install dependencies
        run: npm install

      # Step 5: Run K6 Load Test using npm
      - name: Run K6 Load Test
        run: npm run test
